# Makefile for EEE203 Labsheets

clean_intermediate:
	rm -rf *.idx *.ilg *.ind *.log *.out *.toc *.aux

clean: clean_intermediate
	rm -rf *.pdf

all: lab1 lab2 lab3 lab4 lab5 lab6 lab7 lab8 lab9 lab10 lab11 lab12 lab13 lab14 lab15 lab16 lab17 lab18 lab19 lab20 lab21 lab22 clean_intermediate

lab1:
	pdflatex lab1
	pdflatex lab1

lab2:
	pdflatex lab2
	pdflatex lab2

lab3:
	pdflatex lab3
	pdflatex lab3

lab4:
	pdflatex lab4
	pdflatex lab4

lab5:
	pdflatex lab5
	pdflatex lab5

lab6:
	pdflatex lab6
	pdflatex lab6

lab7:
	pdflatex lab7
	pdflatex lab7

lab8:
	pdflatex lab8
	pdflatex lab8

lab9:
	pdflatex lab9
	pdflatex lab9

lab10:
	pdflatex lab10
	pdflatex lab10

lab11:
	pdflatex lab11
	pdflatex lab11

lab12:
	pdflatex lab12
	pdflatex lab12

lab13:
	pdflatex lab13
	pdflatex lab13

lab14:
	pdflatex lab14
	pdflatex lab14

lab15:
	pdflatex lab15
	pdflatex lab15

lab16:
	pdflatex lab16
	pdflatex lab16

lab17:
	pdflatex lab17
	pdflatex lab17

lab18:
	pdflatex lab18
	pdflatex lab18
	
	
lab19:
	pdflatex lab19
	pdflatex lab19

lab20:
	pdflatex lab20
	pdflatex lab20

lab21:
	pdflatex lab21
	pdflatex lab21
	
lab22:
	pdflatex lab22
	pdflatex lab22








